frases_do_dia = [
  "'O ignorante afirma, o sábio duvida, o sensato reflete.' — Aristóteles",
  "'Nossas dúvidas são traidoras e nos fazem perder o que, com frequência, poderíamos ganhar, por simples medo de arriscar.' — William Shakespeare",
  "'Querias ser livre. Para essa liberdade, só há um caminho: o desprezo das coisas que não dependem de nós.' — Epicteto",
  "'A dor é inevitável, já o sofrimento, completamente opcional.' — Pain",
  "'O mundo é impiedoso, e exatamente por isso, lindo.' — Hajime Isayama",
  "'Uma boa pessoa? Bem... eu não gosto desse termo. Pra mim, isso só significa uma boa pessoa para você. E eu não acho que exista alguém bom para todos.' — Armin Arlert",
  "'Se você ganhar, você vive. Se você perder, você morre. Se você não lutar, não pode vencer. Lute! Lute!' — Eren Jaeger",
  "'Não existe nada que te prive da liberdade além da ignorância.' — Hajime Isayama",
  "A única coisa que podemos fazer é acreditar que não vamos nos arrepender da escolha que fizemos.' — Hajime Isayama",
  "'Palavras bonitas não podem mudar o mundo.' — Lelouch Lamperouge",
  "'Se o Rei não se mover, seus súditos não irão segui-lo.' — Zero",
  "'Não importa o quanto se tente mudá-lo, o mundo continua o mesmo.' — Lelouch Lamperouge",
  "'Uma vida sem mudanças não se chama “vida”. Você apenas pode chama-lá de “experiência”.' — Lelouch Vi Britannia",
  "'O que você fará quando houver um mal que não pode ser derrotado por justiça? Você derrotará o mal com mal ou aceitará que sua justiça pereça diante do mal?' — Zero",
  "'Falsas lágrimas são capazes de machucar outras pessoas. Falsos sorrisos são capazes de machucar a sí mesmo.' — C.C.",
  "Todos procuram por esperança. Vencer significa atropelar isso. Inimigos e aliados são iguais. Porque estamos procurando por algo…' — Schneizel el Britannia",
  "'Isso mesmo. Destruição é necessária antes da reconstrução. Se meus sentimentos se tornarem um problema no processo, será melhor eliminá-los.' — Zero",
  "'Objetivos alcançados de modos errados são objetivos errados' — Kururugi Suzaku",
  "'A partir daquele dia eu estive mentindo pra mim mesmo… O fato de que eu estou vivo é uma mentira… Meu nome é uma mentira. Minha história é uma mentira. Cheia de mentiras… Estando farto de um mundo que não muda nunca, mas sou incapaz de desistir do desespero dessa mentira, de que ele vai mudar.' — Lelouch Vi Britannia",
  "'Mesmo sabendo que há várias coisas que não se pode esquecer e várias coisas tristes também, amanhã continuará vindo, não é?' — Shirley Fenette",
  "'Sentimentos são como rochas que são construídas no nosso coração. Seriam essas rochas os restos de ontem ou os fundamentos do amanhã?' — Lelouch Lamperouge",
  "'Não desista, não há vergonha em cair! A verdadeira vergonha é não se levantar novamente!' — Shintaro Midorima",
  "'Você pode morrer a qualquer momento, mas viver requer coragem.' — Kenshin Himura",
  "'É mais importante dominar as cartas que você tem nas mãos do que reclamar das cartas que seu oponente recebeu.' — Grimsley",
  "'Se você não gosta do seu destino, não o aceite. Em vez disso, tenha a coragem para transformá-lo naquilo que você quer que ele seja.' — Sem autor",
  "'O mundo não é perfeito. Mas ele está aqui para nós, fazendo o melhor que pode... e é isso que o faz tão lindo!' — Roy Mustang",
  "'O que quer que você perca, você encontrará novamente. Mas aquilo que jogar fora, você nunca terá de volta.' — Kenshin Himura",
  "'Mesmo que nós esqueçamos os rostos dos nossos amigos, jamais esqueceremos os laços que foram cravados nas nossas almas.' — Otonashi Yuzuru",
  "'Há momentos que você precisa desistir de alguma coisa para preservar a outra.' — Rize",
  "'Se você aceita tudo sem ao menos questionar, vai acabar perdendo a capacidade de pensar.' — Pandora",
  "'Está tudo bem. Nós nunca estaremos separados. Contanto que estejamos vivos, nos encontraremos sempre.' — Angel Sanctuary",
  "'Seres humanos morrem. Animais morrem. Plantas morrem. Até os ceifadores de almas morrem. É o arco do universo. Tudo o que ganha vida acaba deixando de existir.' — Baraggan Louisenbairn",
  "'Eu estou cansado de não fazer nada, mas eu sou muito preguiçoso pra fazer alguma coisa.' — Hikki",
  "'Esta é uma peça mágica que suprime meus poderes mágicos. Se eu fosse tirar isso, uma grande catástrofe certamente aconteceria neste mundo ... Ah, mentira. Eu só a uso mesmo para deixar o look mais estiloso. — Magumin",
  "'Se você desviar os olhos das coisas tristes, elas acontecerão novamente um dia. Se você continuar fugindo, continuará repetindo os mesmos erros. É por isso que você precisa encarar a verdade diretamente.' — Riki Naoe",
  "'O medo não é malvado. Ele te mostra qual é a sua franqueza. E quando você conhece a sua franqueza, então pode se tornar mais forte e mais gentil.' — Gildarts Clive",
  "'Se as pessoas acreditam em tudo que ouvem, então não há diferença entre a mentira e a verdade.' — Kuroshitsuji",
  "'O que é importante não é o que os outros pensam de você, mas como você age perante a isso.' — Alguém de Nanatsu",
  "'A fim de ganhar algo, deve sacrificar um outro de valor equivalente. Essa é a lei da Alquimia. — Edward Elric",
  "'Ensinamentos obtidos sem sofrimento são desprovidos de valor.' — Edward Elric",
  "You are a great person."
]
suguestão = [
  "Ijiranaide, Nagatoro-san\nhttps://myanimelist.net/anime/42361/Ijiranaide_Nagatoro-san",
  "Fumetsu no Anata e\nhttps://myanimelist.net/anime/41025/Fumetsu_no_Anata_e",
  "Tokyo Revengers\nhttps://myanimelist.net/anime/42249/Tokyo_Revengers",
  "Holo no Graffiti\nhttps://myanimelist.net/anime/44042/Holo_no_Graffiti",
  "Vivy: Fluorite Eye's Song\nhttps://myanimelist.net/anime/46095/Vivy__Fluorite_Eyes_Song",
  "Violet Evergarden\nhttps://myanimelist.net/anime/33352/Violet_Evergarden",
  "Shigatsu wa Kimi no Uso\nhttps://myanimelist.net/anime/23273/Shigatsu_wa_Kimi_no_Uso",
  "Koe no Katachi\nhttps://myanimelist.net/anime/28851/Koe_no_Katachi",
  "Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.\nhttps://myanimelist.net/anime/9989/Ano_Hi_Mita_Hana_no_Namae_wo_Bokutachi_wa_Mada_Shiranai",
  "Kimi no Na wa.\nhttps://myanimelist.net/anime/32281/Kimi_no_Na_wa",
  "Charlotte\nhttps://myanimelist.net/anime/28999/Charlotte",
  "Boku dake ga Inai Machi\nhttps://myanimelist.net/anime/31043/Boku_dake_ga_Inai_Machi",
  "Code Geass: Hangyaku no Lelouch\nhttps://myanimelist.net/anime/1575/Code_Geass__Hangyaku_no_Lelouch",
  "Steins;Gate\nhttps://myanimelist.net/anime/9253/Steins_Gate",
  "Re:Zero kara Hajimeru Isekai Seikatsu\nhttps://myanimelist.net/anime/31240/Re_Zero_kara_Hajimeru_Isekai_Seikatsu",
  "Sword Art Online\nhttps://myanimelist.net/anime/11757/Sword_Art_Online",
  "Kono Subarashii Sekai ni Shukufuku wo!\nhttps://myanimelist.net/anime/30831/Kono_Subarashii_Sekai_ni_Shukufuku_wo",
  "No Game No Life\nhttps://myanimelist.net/anime/19815/No_Game_No_Life",
  "Kimi no Iru Machi\nhttps://myanimelist.net/anime/17741/Kimi_no_Iru_Machi",
  "True Tears\nhttps://myanimelist.net/anime/2129/True_Tears",
  "White Album\nhttps://myanimelist.net/anime/4720/White_Album",
  "School Days\nhttps://myanimelist.net/anime/2476/School_Days",
  "Monster\nhttps://myanimelist.net/anime/19/Monster",
  "Made in Abyss\nhttps://myanimelist.net/anime/34599/Made_in_Abyss",
  "Vinland Saga\nhttps://myanimelist.net/anime/37521/Vinland_Saga",
  "Elfen Lied\nhttps://myanimelist.net/anime/226/Elfen_Lied",
  "Vampire Knight\nhttps://myanimelist.net/anime/3457/Vampire_Knight",
  "Rosario to Vampire\nhttps://myanimelist.net/anime/2993/Rosario_to_Vampire",
  "Toradora!\nhttps://myanimelist.net/anime/4224/Toradora",
  "Chuunibyou demo Koi ga Shitai!\nhttps://myanimelist.net/anime/14741/Chuunibyou_demo_Koi_ga_Shitai",
  "Yahari Ore no Seishun Love Comedy wa Machigatteiru.\nhttps://myanimelist.net/anime/14813/Yahari_Ore_no_Seishun_Love_Comedy_wa_Machigatteiru",
  "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e\nhttps://myanimelist.net/anime/35507/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_TV",
  "Hyouka\nhttps://myanimelist.net/anime/12189/Hyouka",
  "3-gatsu no Lion\nhttps://myanimelist.net/anime/31646/3-gatsu_no_Lion",
  "Howl's Moving Castle\nhttps://myanimelist.net/anime/431/Howl_no_Ugoku_Shiro",
  "Sen to Chihiro no Kamikakushi\nhttps://myanimelist.net/anime/199/Sen_to_Chihiro_no_Kamikakushi",
  "Mononoke Hime\nhttps://myanimelist.net/anime/164/Mononoke_Hime",
  "Tengen Toppa Gurren Lagann\nhttps://myanimelist.net/anime/2001/Tengen_Toppa_Gurren_Lagann",
  "Cowbow Bebop\nhttps://myanimelist.net/anime/1/Cowboy_Bebop",
  "Mushishi Zoku Shou\nhttps://myanimelist.net/anime/21939/Mushishi_Zoku_Shou",
  "Kimi no Suizou wo Tabetai\nhttps://myanimelist.net/anime/36098/Kimi_no_Suizou_wo_Tabetai",
  "One Punch Man\nhttps://myanimelist.net/anime/30276/One_Punch_Man",
  "Uchuu Kyoudai\nhttps://myanimelist.net/anime/12431/Uchuu_Kyoudai",
  "Perfect Blue\n https://myanimelist.net/anime/437/Perfect_Blue",
  "Banana Fish\n https://myanimelist.net/anime/36649/Banana_Fish",
]
traps = [
  "https://static.zerochan.net/Saber.%28Astolfo%29.full.3011262.png",
  "https://static.zerochan.net/Saber.%28Astolfo%29.full.2784350.png",
  "https://static.zerochan.net/Saber.%28Astolfo%29.full.2814588.png",
  "https://static.zerochan.net/Saber.%28Astolfo%29.full.3006281.png",
  "https://static.zerochan.net/Felix.Argyle.full.2018176.jpg",
  "https://static.zerochan.net/Felix.Argyle.full.2012123.jpg",
  "https://static.zerochan.net/Kinoshita.Hideyoshi.full.986490.jpg",
  "https://static.zerochan.net/Kinoshita.Hideyoshi.full.161684.jpg",
  "https://static.zerochan.net/Kinoshita.Hideyoshi.full.416806.jpg",
  "https://static.zerochan.net/Amane.Nishiki.full.1246052.jpg",
  "https://static.zerochan.net/Amane.Nishiki.full.1426197.jpg",
  "https://static.zerochan.net/Amane.Nishiki.full.1399837.jpg",
  "https://static.zerochan.net/Cross-Over.full.965276.jpg",
  "https://static.zerochan.net/Fisheye.full.3183737.jpg",
  "https://static.zerochan.net/Fisheye.full.3153944.jpg",
  "https://static.zerochan.net/Fisheye.full.3169836.jpg",
  "https://static.zerochan.net/Hacka.Doll.No..3.full.1956604.jpg",
  "https://static.zerochan.net/Hacka.Doll.No..3.full.1958301.jpg",
  "https://static.zerochan.net/Arikawa.Hime.full.1796751.jpg",
  "https://static.zerochan.net/Arikawa.Hime.full.2119363.jpg",
  "https://static.zerochan.net/Arikawa.Hime.full.2626797.jpg",
  "https://static.zerochan.net/Arikawa.Hime.full.2119364.jpg",
  "https://static.zerochan.net/Arikawa.Hime.full.2255298.png",
  "https://static.zerochan.net/Arikawa.Hime.full.2213820.png",
  "https://static.zerochan.net/Yuuki.Kei.full.537233.jpg",
  "https://static.zerochan.net/Moyashimon.full.513110.jpg",
  "https://static.zerochan.net/Ansatsu.Kyoushitsu.full.1924891.jpg",
  "https://static.zerochan.net/Shiota.Nagisa.full.1929898.jpg"
]
bichos = [
  "Cão de Guarda"
]
banners = [
  "https://imgur.com/H6pKvIH"
]

## Personagens ##

nomesh = [
  "Naru",
  "Oye",
  "Igarashi",
  "Asai",
  "Matsushita",
  "Yashiro",
  "Oki",
  "Murata",
  "Oogami",
  "Uchibayase",
  "Sakiyama",
  "Akibara",
  "Miyamoto",
  "Ouji",
  "Okumura",
  "Wakatanabe",
  "Miyasato",
  "Takamori",
  "Takamoto",
  "Mizutani",
]
sobrenomeh = [
  "Kanbe",
  "Gyokusho",
  "Susumo",
  "Kojiro",
  "Norihide",
  "Sasekien",
  "Matsudarai",
  "Ryoko",
  "Masanori",
  "Kazuhiro",
  "Danjuro",
  "Mamoru",
  "Seishiro",
  "Tomoeio",
  "Kenji",
  "Muneyaki",
  "Takamasa",
  "Kazuhiko",
  "Mitsunari",
  "Yasuhito",
]
menos25 = [
  "Estudante",
  "Entrgador",
  "Estudante de Intercâmbio",
  "Attendente",
  "Garçom",
  "Vendedor",
  "Estudante de Artes",
  "Atleta",
  "Capitão do Time de Futebol",
  "Presidente do Conselho Estudantil",
  "Estudante Transferido"
]
mais26 = [
  'Médico',
  'Day Trader',
  'Advogado',
  'Professor',
  "Engenheiro Civil",
  "Policial",
  "Detetive",
  "Construtor",
  "Assistente de Construção",
  "Programador"
]
sangue = [
  'A',
  'B',
  'O',
  'AB'
]
sanguemm = [
  '+',
  '-'
]
personalidades = [
  'Lógico',
  'Estratégico',
  'Independete',
  'Reservado',
  'Adaptável',
  'Criativo',
  'Líder',
  'Sociável',
  'Comandante',
  'Confiante',
  'Explosivo',
  'Cooperativo',
  'Aventureiro',
  'Observador'
]
menos25m = [
  'Cavaleiro em Treinamento',
  'Arqueiro em Treinamento',
  'Escravo',
  'Aprendiz de Feiriceiro',
  'Aprendiz de Curandeiro',
  'Estudante na academia de artes marciais'
]
mais26m = [
  'Cavaleiro Real',
  'Arqueiro',
  'Espadachim',
  'Mago/Bruxa',
  'Curandeira(o)'
]
mahaa = [
  'Eu kimetsu no seu rayba, locão de juju na cara\nSe o Sol não te queimar\nOniMinha katana te rasga',
  'Para de brigar net, hater é tudo otário\nVem brigar com meu Mike Tyson que dá soco no teu rabo',
  'Ela é da gangue do Valhalla, Valhalla, Valhalla\nVai, rala a tcheca na peça, vai, rala a tcheca na caixa',
  'Andam dizendo que o sukuna é o demônio\nAham mas eu que sou o demônio socando',
  'Misato me mamou em cima do robô\nDesliza no LCL, vem jogando esse popô',
  'De dia eu sou o Bruce Wayne\nAmo quando as notas vem\nFaço o corre direitinho\nPra bancar minhas neném',
]
japa = [
'https://javhd.pics/media/japanese/yua-mikami/64/hd-yua-mikami-11.jpg',
'https://javhd.pics/media/japanese/yua-mikami/64/hd-yua-mikami-1.jpg',
'https://javhd.pics/media/japanese/yua-mikami/64/hd-yua-mikami-2.jpg',
'https://javhd.pics/media/japanese/yua-mikami/24/hd-yua-mikami-1.jpg',
'https://javhd.pics/media/japanese/yua-mikami/24/hd-yua-mikami-2.jpg',
'https://javhd.pics/media/japanese/yua-mikami/24/hd-yua-mikami-3.jpg',
'https://javhd.pics/media/japanese/yua-mikami/24/hd-yua-mikami-4.jpg',
'https://javhd.pics/media/japanese/yua-mikami/54/hd-yua-mikami-2.jpg',
'https://javhd.pics/media/japanese/yua-mikami/54/hd-yua-mikami-3.jpg',
'https://javhd.pics/media/japanese/yua-mikami/60/hd-yua-mikami-7.jpg',
'https://javhd.pics/media/japanese/yua-mikami/60/hd-yua-mikami-10.jpg',
'https://javhd.pics/media/japanese/yua-mikami/30/hd-yua-mikami-1.jpg',
]

## GIFS ##

beijo = [
  'https://media.giphy.com/media/FqBTvSNjNzeZG/giphy.gif',
  'https://media.giphy.com/media/N3IuFaIanEs6I/giphy.gif',
  'https://media.giphy.com/media/jR22gdcPiOLaE/giphy.gif',
  'https://media.giphy.com/media/87vvTexnItOkE/giphy.gif',
  'https://media.giphy.com/media/12VXIxKaIEarL2/giphy.gif',
  'https://media.giphy.com/media/G3va31oEEnIkM/giphy.gif',
  'https://media.giphy.com/media/zkppEMFvRX5FC/giphy.gif',
  'https://media.giphy.com/media/kU586ictpGb0Q/giphy.gif',
  'https://media.giphy.com/media/bm2O3nXTcKJeU/giphy.gif',
  'https://media.giphy.com/media/nyGFcsP0kAobm/giphy.gif',
  'https://media.giphy.com/media/QGc8RgRvMonFm/giphy.gif',
  'https://c.tenor.com/3wE3JNW0fswAAAAC/anime-kiss-love.gif',
  'https://c.tenor.com/e6cYiAPPCq4AAAAC/anime-kissing.gif',
  'https://c.tenor.com/bkF2kFvXR50AAAAC/yes-love.gif',
  'https://c.tenor.com/hjhEoMvMTOIAAAAC/girls-anime.gif',
]
abraço = [
  'https://media.giphy.com/media/WynnqxhdFEPYY/giphy.gif',
  'https://media.giphy.com/media/du8yT5dStTeMg/giphy.gif',
  'https://media.giphy.com/media/3ZnBrkqoaI2hq/giphy.gif',
  'https://media.giphy.com/media/ZQN9jsRWp1M76/giphy.gif',
  'https://media.giphy.com/media/aD1fI3UUWC4/giphy.gif',
  'https://media.giphy.com/media/QFPoctlgZ5s0E/giphy.gif',
  'https://media.giphy.com/media/svXXBgduBsJ1u/giphy.gif',
  'https://media.giphy.com/media/3bqtLDeiDtwhq/giphy.gif',
  'https://media.giphy.com/media/wSY4wcrHnB0CA/giphy.gif',
  'https://media.giphy.com/media/5eyhBKLvYhafu/giphy.gif',
  'https://media.giphy.com/media/lrr9rHuoJOE0w/giphy.gif',
  'https://media.giphy.com/media/od5H3PmEG5EVq/giphy.gif',
  'https://media.giphy.com/media/wnsgren9NtITS/giphy.gif',
  'https://media.giphy.com/media/kvKFM3UWg2P04/giphy.gif',
  'https://media.giphy.com/media/yziFo5qYAOgY8/giphy.gif',
  'https://c.tenor.com/Ct4bdr2ZGeAAAAAC/teria-wang-kishuku-gakkou-no-juliet.gif',
  'https://c.tenor.com/xgVPw2QK5n8AAAAC/sakura-quest-anime.gif',
  'https://c.tenor.com/X5nBTYuoKpoAAAAC/anime-cheeks.gif',
  'https://c.tenor.com/9e1aE_xBLCsAAAAC/anime-hug.gif',
  'https://c.tenor.com/X5nBTYuoKpoAAAAC/anime-cheeks.gif',
  'https://c.tenor.com/sBFE3GeNpJ4AAAAC/tackle-hug-couple.gif',
  'https://c.tenor.com/ixaDEFhZJSsAAAAS/anime-choke.gif',
  'https://c.tenor.com/zirc8LTWVUkAAAAC/hug-anime.gif',
  'https://c.tenor.com/GJ6oX6r0mZsAAAAC/chuunibyou-anime.gif',
]
nani = [
  'https://static.hentai-gif-anime.com/upload/20160529/16/32051/1.gif',
  'https://static.hentai-gif-anime.com/upload/20160504/9/18093/detail.gif',
  'https://static.hentai-gif-anime.com/upload/20160529/16/32049/1.gif',
  'https://static.hentai-gif-anime.com/upload/20160529/16/32054/1.gif',
  'https://wetgif.com/wp-content/uploads/gif-hentai-incest-11-22.gif',
  'https://wetgif.com/wp-content/uploads/gif-hentai-incest-36.gif',
  'https://wetgif.com/wp-content/uploads/hentai-23.gif',
  'https://wetgif.com/wp-content/uploads/porno-anime-68.gif',
  'https://wetgif.com/wp-content/uploads/gif-hentai-incest-40.gif',
  'https://wetgif.com/wp-content/uploads/gif-hentai-incest-36.gif',
]
