qotd = [
  "'O ignorante afirma, o sábio duvida, o sensato reflete.' — Aristóteles",
  "'Nossas dúvidas são traidoras e nos fazem perder o que, com frequência, poderíamos ganhar, por simples medo de arriscar.' — William Shakespeare",
  "'Querias ser livre. Para essa liberdade, só há um caminho: o desprezo das coisas que não dependem de nós.' — Epicteto",
  "'A dor é inevitável, já o sofrimento, completamente opcional.' — Pain",
  "'O mundo é impiedoso, e exatamente por isso, lindo.' — Hajime Isayama",
  "'Uma boa pessoa? Bem... eu não gosto desse termo. Pra mim, isso só significa uma boa pessoa para você. E eu não acho que exista alguém bom para todos.' — Armin Arlert",
  "'Se você ganhar, você vive. Se você perder, você morre. Se você não lutar, não pode vencer. Lute! Lute!' — Eren Jaeger",
  "'Não existe nada que te prive da liberdade além da ignorância.' — Hajime Isayama",
  "A única coisa que podemos fazer é acreditar que não vamos nos arrepender da escolha que fizemos.' — Hajime Isayama",
  "'Palavras bonitas não podem mudar o mundo.' — Lelouch Lamperouge",
  "'Se o Rei não se mover, seus súditos não irão segui-lo.' — Zero",
  "'Não importa o quanto se tente mudá-lo, o mundo continua o mesmo.' — Lelouch Lamperouge",
  "'Uma vida sem mudanças não se chama “vida”. Você apenas pode chama-lá de “experiência”.' — Lelouch Vi Britannia",
  "'O que você fará quando houver um mal que não pode ser derrotado por justiça? Você derrotará o mal com mal ou aceitará que sua justiça pereça diante do mal?' — Zero",
  "'Falsas lágrimas são capazes de machucar outras pessoas. Falsos sorrisos são capazes de machucar a sí mesmo.' — C.C.",
  "Todos procuram por esperança. Vencer significa atropelar isso. Inimigos e aliados são iguais. Porque estamos procurando por algo…' — Schneizel el Britannia",
  "'Isso mesmo. Destruição é necessária antes da reconstrução. Se meus sentimentos se tornarem um problema no processo, será melhor eliminá-los.' — Zero",
  "'Objetivos alcançados de modos errados são objetivos errados' — Kururugi Suzaku",
  "'A partir daquele dia eu estive mentindo pra mim mesmo… O fato de que eu estou vivo é uma mentira… Meu nome é uma mentira. Minha história é uma mentira. Cheia de mentiras… Estando farto de um mundo que não muda nunca, mas sou incapaz de desistir do desespero dessa mentira, de que ele vai mudar.' — Lelouch Vi Britannia",
  "'Mesmo sabendo que há várias coisas que não se pode esquecer e várias coisas tristes também, amanhã continuará vindo, não é?' — Shirley Fenette",
  "'Sentimentos são como rochas que são construídas no nosso coração. Seriam essas rochas os restos de ontem ou os fundamentos do amanhã?' — Lelouch Lamperouge",
  "'Não desista, não há vergonha em cair! A verdadeira vergonha é não se levantar novamente!' — Shintaro Midorima",
  "'Você pode morrer a qualquer momento, mas viver requer coragem.' — Kenshin Himura",
  "'É mais importante dominar as cartas que você tem nas mãos do que reclamar das cartas que seu oponente recebeu.' — Grimsley",
  "'Se você não gosta do seu destino, não o aceite. Em vez disso, tenha a coragem para transformá-lo naquilo que você quer que ele seja.' — Sem autor",
  "'O mundo não é perfeito. Mas ele está aqui para nós, fazendo o melhor que pode... e é isso que o faz tão lindo!' — Roy Mustang",
  "'O que quer que você perca, você encontrará novamente. Mas aquilo que jogar fora, você nunca terá de volta.' — Kenshin Himura",
  "'Mesmo que nós esqueçamos os rostos dos nossos amigos, jamais esqueceremos os laços que foram cravados nas nossas almas.' — Otonashi Yuzuru",
  "'Há momentos que você precisa desistir de alguma coisa para preservar a outra.' — Rize",
  "'Se você aceita tudo sem ao menos questionar, vai acabar perdendo a capacidade de pensar.' — Pandora",
  "'Está tudo bem. Nós nunca estaremos separados. Contanto que estejamos vivos, nos encontraremos sempre.' — Angel Sanctuary",
  "'Seres humanos morrem. Animais morrem. Plantas morrem. Até os ceifadores de almas morrem. É o arco do universo. Tudo o que ganha vida acaba deixando de existir.' — Baraggan Louisenbairn",
  "'Eu estou cansado de não fazer nada, mas eu sou muito preguiçoso pra fazer alguma coisa.' — Hikki",
  "'Esta é uma peça mágica que suprime meus poderes mágicos. Se eu fosse tirar isso, uma grande catástrofe certamente aconteceria neste mundo ... Ah, mentira. Eu só a uso mesmo para deixar o look mais estiloso. — Magumin",
  "'Se você desviar os olhos das coisas tristes, elas acontecerão novamente um dia. Se você continuar fugindo, continuará repetindo os mesmos erros. É por isso que você precisa encarar a verdade diretamente.' — Riki Naoe",
  "'O medo não é malvado. Ele te mostra qual é a sua franqueza. E quando você conhece a sua franqueza, então pode se tornar mais forte e mais gentil.' — Gildarts Clive",
  "'Se as pessoas acreditam em tudo que ouvem, então não há diferença entre a mentira e a verdade.' — Kuroshitsuji",
  "'O que é importante não é o que os outros pensam de você, mas como você age perante a isso.' — Alguém de Nanatsu",
  "'A fim de ganhar algo, deve sacrificar um outro de valor equivalente. Essa é a lei da Alquimia. — Edward Elric",
  "'Ensinamentos obtidos sem sofrimento são desprovidos de valor.' — Edward Elric",
  "You are a great person."
]

mahaa = [
  'Eu kimetsu no seu rayba, locão de juju na cara\nSe o Sol não te queimar\nOniMinha katana te rasga',
  'Para de brigar net, hater é tudo otário\nVem brigar com meu Mike Tyson que dá soco no teu rabo',
  'Ela é da gangue do Valhalla, Valhalla, Valhalla\nVai, rala a tcheca na peça, vai, rala a tcheca na caixa',
  'Andam dizendo que o sukuna é o demônio\nAham mas eu que sou o demônio socando',
  'Misato me mamou em cima do robô\nDesliza no LCL, vem jogando esse popô',
  'De dia eu sou o Bruce Wayne\nAmo quando as notas vem\nFaço o corre direitinho\nPra bancar minhas neném',
]